// apps/examples/angular/list/src/app/app.component.ts
import { Component } from '@angular/core';
import { FormControl } from '@angular/forms';
import {
  customListImpl$ as listViewModel$,
  // reducerListImpl$ as listViewModel$,
  ListViewModel,
} from '@derxjs/examples/list-view-model-implementation';
import { Observable, Observer } from 'rxjs';

@Component({
  selector: 'derxjs-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  textInputFormControl = new FormControl();
  private _pushObserver!: Observer<string>;
  private _popObserver!: Observer<void>;
  viewModel$: Observable<ListViewModel>;

  constructor() {
    const push$ = new Observable<string>(
      (observer) => (this._pushObserver = observer)
    );
    const pop$ = new Observable<void>(
      (observer) => (this._popObserver = observer)
    );
    this.viewModel$ = listViewModel$({ push$, pop$, initialValue: [] }) as any;
  }

  push() {
    this._pushObserver.next(this.textInputFormControl.value);
    this.textInputFormControl.reset();
  }

  pop() {
    this._popObserver.next();
  }
}

<ng-container *ngIf="viewModel$ | async as viewModel">
  <h1>@derxj/view-model Angular Usage Example</h1>

  <form>
    <input type="text" [formControl]="textInputFormControl" />
    <button (click)="push()">Push</button>
  </form>

  <ul>
    <li *ngFor="let item of viewModel">{{ item }}</li>
  </ul>

  <button (click)="pop()">Pop</button>
</ng-container>

// apps/examples/react/list/src/app/app.tsx
import {
  customListImpl$,
  ListViewModel,
  ListViewModelInputs,
} from '@derxjs/examples/list-view-model-implementation';
import { DeRxJSViewModel } from 'packages/view-model/src/lib/view-model';
import { useEffect, useState } from 'react';
import { Observable, Observer } from 'rxjs';

let pushObserver: Observer<string>;
let popObserver: Observer<void>;
const push$ = new Observable<string>((observer) => (pushObserver = observer));
const pop$ = new Observable<void>((observer) => (popObserver = observer));

const ViewModelComponent = (
  viewModel: DeRxJSViewModel<ListViewModelInputs, ListViewModel>,
  component: ({
    viewModel,
    pushClick,
    popClick,
  }: {
    viewModel: ListViewModel;
    pushClick: (x: string) => void;
    popClick: () => void;
  }) => any
) => {
  const [viewModelValue, setViewModel] = useState([] as ListViewModel);
  const pushClick = (value: string) => pushObserver.next(value);
  const popClick = () => popObserver.next();
  useEffect(() => {
    const subscription = viewModel({ push$, pop$, initialValue: [] }).subscribe(
      (x) => setViewModel(x)
    );
    return () => subscription.unsubscribe();
  }, []);
  return component({ viewModel: viewModelValue, popClick, pushClick });
};

function ListView({
  viewModel,
  pushClick,
  popClick,
}: {
  viewModel: ListViewModel;
  pushClick: (x: string) => void;
  popClick: () => void;
}) {
  const handlePush = (e: any) => {
    e.preventDefault();
    const textInput = document.getElementById('textInput')! as HTMLInputElement;
    const formValue = textInput.value;
    pushClick(formValue);
    textInput.value = '';
  };

  return (
    <div>
      <h1>@derxj/view-model React Usage Example</h1>
      <form>
        <input type="text" id="textInput" />
        <button onClick={handlePush}>Push</button>
      </form>
      <ul>
        {viewModel.map((item, i) => (
          <li key={i}>{item}</li>
        ))}
      </ul>
      <button onClick={popClick}>Pop</button>
    </div>
  );
}

export const App = () => {
  return ViewModelComponent(customListImpl$, ListView);
};

export default App;
